INSERT INTO  Dim_Precedure_Type
( Procedure_Type_ID, Procedure_Names,Descriptions,Procedure_Category )
VALUES
(1, 'Coronary Angioplasty', 'Minimally invasive procedure to open blocked heart arteries', 'Cardiology'),
(2, 'Pacemaker Implantation', 'Device implanted to regulate abnormal heart rhythms', 'Cardiology'),
(3, 'Cardiac Bypass Surgery', 'Surgical procedure to restore blood flow to the heart', 'Cardiology'),
(4, 'Echocardiogram', 'Ultrasound imaging of the heart', 'Cardiology'),
(5, 'Stress Test', 'Exercise-based test to evaluate heart function', 'Cardiology'),
(6, 'Chemotherapy Infusion', 'Administration of anti-cancer drugs intravenously', 'Oncology'),
(7, 'Radiation Therapy', 'Targeted radiation treatment for cancer cells', 'Oncology'),
(8, 'Biopsy', 'Removal of tissue sample for cancer diagnosis', 'Oncology'),
(9, 'Bone Marrow Transplant', 'Replacement of diseased bone marrow with healthy cells', 'Oncology'),
(10, 'Immunotherapy', 'Treatment using immune system modulators', 'Oncology'),
(11, 'EEG (Electroencephalogram)', 'Brain activity monitoring using electrodes', 'Neurology'),
(12, 'MRI Brain Scan', 'Magnetic imaging of brain structures', 'Neurology'),
(13, 'Lumbar Puncture', 'Spinal fluid extraction for diagnostic testing', 'Neurology'),
(14, 'Stroke Thrombolysis', 'Emergency clot-busting treatment for stroke', 'Neurology'),
(15, 'Epilepsy Surgery', 'Surgical removal of seizure-causing brain tissue', 'Neurology'),
(16, 'Hip Replacement', 'Surgical replacement of damaged hip joint', 'Orthopedics'),
(17, 'Knee Arthroscopy', 'Minimally invasive knee joint examination', 'Orthopedics'),
(18, 'Fracture Fixation', 'Surgical repair of broken bones', 'Orthopedics'),
(19, 'Spinal Fusion', 'Surgical joining of vertebrae to stabilize spine', 'Orthopedics'),
(20, 'Shoulder Reconstruction', 'Repair of damaged shoulder ligaments or bones', 'Orthopedics'),
(21, 'Cesarean Section', 'Surgical delivery of a baby through the abdomen', 'Maternity'),
(22, 'Normal Vaginal Delivery', 'Natural childbirth procedure', 'Maternity'),
(23, 'Epidural Anesthesia', 'Pain relief injection during labor', 'Maternity'),
(24, 'Fetal Monitoring', 'Continuous monitoring of fetal heart rate', 'Maternity'),
(25, 'Dilation and Curettage', 'Procedure to remove tissue from uterus', 'Maternity'),
(26, 'Appendectomy', 'Surgical removal of the appendix', 'General Surgery'),
(27, 'Gallbladder Removal', 'Surgical removal of gallbladder (cholecystectomy)', 'General Surgery'),
(28, 'Hernia Repair', 'Surgical correction of hernia', 'General Surgery'),
(29, 'Tonsillectomy', 'Removal of tonsils', 'General Surgery'),
(30, 'Thyroidectomy', 'Surgical removal of thyroid gland', 'General Surgery'),
(31, 'Bronchoscopy', 'Endoscopic examination of airways', 'Respiratory'),
(32, 'Lung Biopsy', 'Tissue sampling from lungs', 'Respiratory'),
(33, 'Thoracentesis', 'Removal of fluid from pleural space', 'Respiratory'),
(34, 'Ventilator Support', 'Mechanical breathing assistance', 'Respiratory'),
(35, 'Pulmonary Function Test', 'Assessment of lung capacity and airflow', 'Respiratory'),
(36, 'Dialysis', 'Blood filtration for kidney failure', 'Nephrology'),
(37, 'Kidney Biopsy', 'Tissue sampling from kidney', 'Nephrology'),
(38, 'Renal Transplant', 'Surgical replacement of diseased kidney', 'Nephrology'),
(39, 'Ureteroscopy', 'Endoscopic examination of urinary tract', 'Nephrology'),
(40, 'Lithotripsy', 'Shockwave treatment to break kidney stones', 'Nephrology'),
(41, 'Pediatric Vaccination', 'Administration of routine childhood vaccines', 'Pediatrics'),
(42, 'Neonatal Intensive Care', 'Specialized care for critically ill newborns', 'Pediatrics'),
(43, 'Circumcision', 'Surgical removal of foreskin in infants', 'Pediatrics'),
(44, 'Pediatric Endoscopy', 'Endoscopic examination for children', 'Pediatrics'),
(45, 'Growth Hormone Therapy', 'Treatment for growth disorders in children', 'Pediatrics'),
(46, 'Ventilator Management', 'Continuous mechanical breathing support', 'ICU'),
(47, 'Central Line Insertion', 'Placement of catheter into large vein', 'ICU'),
(48, 'Arterial Line Monitoring', 'Continuous blood pressure monitoring via artery', 'ICU'),
(49, 'Tracheostomy', 'Surgical airway opening in neck', 'ICU'),
(50, 'Sedation Management', 'Administration of sedatives for critical patients', 'ICU'),
(51, 'CPR (Cardiopulmonary Resuscitation)', 'Emergency resuscitation procedure', 'Emergency'),
(52, 'Defibrillation', 'Electric shock to restore heart rhythm', 'Emergency'),
(53, 'Trauma Surgery', 'Immediate surgical intervention for trauma', 'Emergency'),
(54, 'Burn Treatment', 'Emergency management of burn injuries', 'Emergency'),
(55, 'Poisoning Management', 'Treatment for toxic ingestion or exposure', 'Emergency'),
(56, 'Gastroscopy', 'Endoscopic examination of stomach', 'Gastroenterology'),
(57, 'ERCP', 'Endoscopic retrograde cholangiopancreatography', 'Gastroenterology'),
(58, 'Hemorrhoidectomy', 'Surgical removal of hemorrhoids', 'Gastroenterology'),
(59, 'Bariatric Surgery', 'Weight loss surgery for obesity', 'Gastroenterology'),
(60, 'Capsule Endoscopy', 'Swallowable camera for GI tract imaging', 'Gastroenterology'),
(61, 'Skin Biopsy', 'Removal of skin tissue for diagnosis', 'Dermatology'),
(62, 'Laser Skin Therapy', 'Laser treatment for skin conditions', 'Dermatology'),
(63, 'Mohs Surgery', 'Precise removal of skin cancer', 'Dermatology'),
(64, 'Cryotherapy', 'Freezing treatment for skin lesions', 'Dermatology'),
(65, 'Phototherapy', 'Light-based treatment for skin disorders', 'Dermatology'),
(66, 'Cataract Surgery', 'Removal and replacement of cloudy lens', 'Ophthalmology'),
(67, 'LASIK Surgery', 'Laser correction of vision', 'Ophthalmology'),
(68, 'Retinal Repair', 'Surgical repair of detached retina', 'Ophthalmology'),
(69, 'Glaucoma Surgery', 'Procedure to reduce eye pressure', 'Ophthalmology'),
(70, 'Corneal Transplant', 'Replacement of damaged cornea', 'Ophthalmology'),
(71, 'Tympanoplasty', 'Surgical repair of eardrum', 'ENT'),
(72, 'Sinus Surgery', 'Endoscopic removal of sinus blockages', 'ENT'),
(73, 'Cochlear Implant', 'Device implantation for hearing loss', 'ENT'),
(74, 'Adenoidectomy', 'Surgical removal of adenoids', 'ENT'),
(75, 'Laryngoscopy', 'Examination of larynx using scope', 'ENT'),
(76, 'Prostate Surgery', 'Surgical removal of prostate tissue', 'Urology'),
(77, 'Cystoscopy', 'Endoscopic examination of bladder', 'Urology'),
(78, 'Vasectomy', 'Male sterilization procedure', 'Urology'),
(79, 'Bladder Reconstruction', 'Surgical repair of bladder', 'Urology'),
(80, 'Orchiectomy', 'Removal of one or both testicles', 'Urology'),
(81, 'Arthroscopy', 'Minimally invasive joint examination', 'Orthopedics'),
(82, 'ACL Reconstruction', 'Repair of torn anterior cruciate ligament', 'Orthopedics'),
(83, 'Meniscus Repair', 'Surgical repair of knee cartilage', 'Orthopedics'),
(84, 'Bone Grafting', 'Transplantation of bone tissue', 'Orthopedics'),
(85, 'Joint Replacement Revision', 'Replacement of failed joint prosthesis', 'Orthopedics'),
(86, 'Spinal Decompression', 'Surgical relief of spinal nerve pressure', 'Orthopedics'),
(87, 'Carpal Tunnel Release', 'Surgical release of wrist nerve compression', 'Orthopedics'),
(88, 'Clubfoot Correction', 'Surgical correction of congenital foot deformity', 'Orthopedics'),
(89, 'Amputation', 'Removal of limb due to trauma or disease', 'Orthopedics'),
(90, 'Vertebroplasty', 'Injection of cement into fractured vertebra', 'Orthopedics'),
(91, 'Bone Marrow Biopsy', 'Sampling of bone marrow for diagnosis', 'Oncology'),
(92, 'Targeted Therapy', 'Precision drugs for specific cancer mutations', 'Oncology'),
(93, 'Cryoablation', 'Freezing treatment for tumors', 'Oncology'),
(94, 'Palliative Care Infusion', 'Symptom relief for advanced cancer patients', 'Oncology'),
(95, 'Oncological Surgery', 'Removal of malignant tumors', 'Oncology'),
(96, 'EEG Monitoring', 'Continuous brain activity monitoring', 'Neurology'),
(97, 'Deep Brain Stimulation', 'Implantation of electrodes for Parkinson’s disease', 'Neurology'),
(98, 'Nerve Conduction Study', 'Assessment of nerve signal transmission', 'Neurology'),
(99, 'Carotid Endarterectomy', 'Surgical removal of plaque from carotid artery', 'Neurology'),
(100, 'Brain Tumor Resection', 'Surgical removal of brain tumor', 'Neurology'),
(101, 'Cesarean Hysterectomy', 'Removal of uterus during C-section', 'Maternity'),
(102, 'Amniocentesis', 'Sampling of amniotic fluid for testing', 'Maternity'),
(103, 'In Vitro Fertilization', 'Assisted reproductive technology procedure', 'Maternity'),
(104, 'Tubal Ligation', 'Permanent female sterilization procedure', 'Maternity'),
(105, 'Placenta Removal', 'Surgical removal of retained placenta', 'Maternity'),
(106, 'Appendectomy (Laparoscopic)', 'Minimally invasive appendix removal', 'General Surgery'),
(107, 'Splenectomy', 'Surgical removal of spleen', 'General Surgery'),
(108, 'Colectomy', 'Partial or total removal of colon', 'General Surgery'),
(109, 'Mastectomy', 'Surgical removal of breast tissue', 'General Surgery'),
(110, 'Parathyroidectomy', 'Surgical removal of parathyroid glands', 'General Surgery'),
(111, 'Bronchial Thermoplasty', 'Heat treatment for severe asthma', 'Respiratory'),
(112, 'Pleurodesis', 'Procedure to prevent recurrent pleural effusion', 'Respiratory'),
(113, 'Endobronchial Ultrasound', 'Ultrasound-guided biopsy of lung tissue', 'Respiratory'),
(114, 'Mechanical Ventilation', 'Artificial breathing support', 'Respiratory'),
(115, 'Sleep Apnea Study', 'Diagnostic study for sleep-related breathing disorders', 'Respiratory'),
(116, 'Renal Angioplasty', 'Procedure to open blocked kidney arteries', 'Nephrology'),
(117, 'Peritoneal Dialysis', 'Dialysis using abdominal lining', 'Nephrology'),
(118, 'Nephrectomy', 'Surgical removal of kidney', 'Nephrology'),
(119, 'Urinary Catheterization', 'Insertion of catheter into bladder', 'Nephrology'),
(120, 'Kidney Stone Removal', 'Surgical removal of kidney stones', 'Nephrology'),
(121, 'Skin Grafting', 'Transplantation of skin tissue', 'Dermatology'),
(122, 'Acne Extraction', 'Manual removal of acne lesions', 'Dermatology'),
(123, 'Dermabrasion', 'Skin resurfacing procedure', 'Dermatology'),
(124, 'Excision of Skin Lesion', 'Surgical removal of abnormal skin growth', 'Dermatology'),
(125, 'Psoriasis Phototherapy', 'Light treatment for psoriasis', 'Dermatology'),
(126, 'Vitrectomy', 'Removal of vitreous gel from eye', 'Ophthalmology'),
(127, 'Eye Muscle Surgery', 'Correction of strabismus (crossed eyes)', 'Ophthalmology'),
(128, 'Intravitreal Injection', 'Injection of medication into eye', 'Ophthalmology'),
(129, 'Ocular Prosthesis', 'Artificial eye implantation', 'Ophthalmology'),
(130, 'Macular Hole Repair', 'Surgical repair of macular defect', 'Ophthalmology'),
(131, 'Septoplasty', 'Correction of deviated nasal septum', 'ENT'),
(132, 'Turbinate Reduction', 'Reduction of nasal turbinates', 'ENT'),
(133, 'Voice Therapy', 'Treatment for vocal cord disorders', 'ENT'),
(134, 'Ear Tube Insertion', 'Placement of tubes in eardrum', 'ENT'),
(135, 'Pharyngoplasty', 'Surgical reconstruction of pharynx', 'ENT'),
(136, 'Prostate Biopsy', 'Sampling of prostate tissue', 'Urology'),
(137, 'Nephrostomy', 'Insertion of tube into kidney', 'Urology'),
(138, 'Penile Prosthesis Implant', 'Implantation for erectile dysfunction', 'Urology'),
(139, 'Hydrocelectomy', 'Removal of fluid-filled sac around testicle', 'Urology'),
(140, 'Urethral Reconstruction', 'Surgical repair of urethra', 'Urology'),
(141, 'Hand Surgery', 'Surgical repair of hand injuries', 'Orthopedics'),
(142, 'Foot Reconstruction', 'Correction of foot deformities', 'Orthopedics'),
(143, 'Arthrodesis', 'Fusion of joint to relieve pain', 'Orthopedics'),
(144, 'Osteotomy', 'Cutting and reshaping of bone', 'Orthopedics'),
(145, 'Ligament Repair', 'Surgical repair of torn ligaments', 'Orthopedics'),
(146, 'Chemotherapy Port Insertion', 'Placement of port for drug delivery', 'Oncology'),
(147, 'Radiofrequency Ablation', 'Heat treatment for tumors', 'Oncology'),
(148, 'Hormone Therapy', 'Treatment using hormone modulators', 'Oncology'),
(149, 'Oncological Imaging', 'Advanced imaging for cancer staging', 'Oncology'),
(150, 'Cancer Screening Colonoscopy', 'Preventive colonoscopy for cancer detection', 'Oncology'),
(151, 'Neurological Rehabilitation', 'Therapy for recovery after brain injury', 'Neurology'),
(152, 'Spinal Tap', 'Diagnostic removal of spinal fluid', 'Neurology'),
(153, 'Cranial Surgery', 'Surgical intervention on skull', 'Neurology'),
(154, 'Peripheral Nerve Repair', 'Surgical repair of damaged nerves', 'Neurology'),
(155, 'Neuroendoscopy', 'Endoscopic procedure for brain ventricles', 'Neurology'),
(156, 'Labor Induction', 'Medical stimulation of childbirth', 'Maternity'),
(157, 'Postpartum Hemorrhage Control', 'Emergency procedure to stop bleeding', 'Maternity'),
(158, 'Amniotic Fluid Drainage', 'Removal of excess amniotic fluid', 'Maternity'),
(159, 'Embryo Transfer', 'Placement of embryo into uterus', 'Maternity'),
(160, 'Ovarian Cyst Removal', 'Surgical removal of ovarian cysts', 'Maternity'),
(161, 'Laparoscopic Hernia Repair', 'Minimally invasive hernia correction', 'General Surgery'),
(162, 'Adrenalectomy', 'Surgical removal of adrenal gland', 'General Surgery'),
(163, 'Pancreatectomy', 'Removal of pancreas tissue', 'General Surgery'),
(164, 'Esophagectomy', 'Surgical removal of esophagus', 'General Surgery'),
(165, 'Small Bowel Resection', 'Removal of diseased small intestine', 'General Surgery'),
(166, 'Lung Transplant', 'Surgical replacement of diseased lung', 'Respiratory'),
(167, 'Chest Tube Insertion', 'Placement of tube to drain chest fluid', 'Respiratory'),
(168, 'Bronchial Stent Placement', 'Insertion of stent into airway', 'Respiratory'),
(169, 'Respiratory Physiotherapy', 'Therapy to improve lung function', 'Respiratory'),
(170, 'Asthma Nebulization', 'Inhalation therapy for asthma', 'Respiratory'),
(171, 'Kidney Transplant', 'Surgical replacement of diseased kidney', 'Nephrology'),
(172, 'Bladder Stone Removal', 'Surgical removal of bladder stones', 'Nephrology'),
(173, 'Renal Ultrasound', 'Imaging of kidneys using ultrasound', 'Nephrology'),
(174, 'Hemodialysis', 'Blood filtration using dialysis machine', 'Nephrology'),
(175, 'Ureteral Stent Placement', 'Insertion of stent into ureter', 'Nephrology'),
(176, 'Laser Skin Resurfacing', 'Laser treatment for wrinkles and scars', 'Dermatology'),
(177, 'Chemical Peel', 'Application of chemical solution to exfoliate and rejuvenate skin', 'Dermatology'),
(178, 'Skin Allergy Testing', 'Diagnostic testing for allergic skin reactions', 'Dermatology'),
(179, 'Wart Removal', 'Cryotherapy or excision of skin warts', 'Dermatology'),
(180, 'Scar Revision Surgery', 'Surgical improvement of scar appearance', 'Dermatology'),
(181, 'Psoriasis Biologic Therapy', 'Targeted biologic treatment for psoriasis', 'Dermatology'),
(182, 'Melanoma Excision', 'Surgical removal of malignant skin melanoma', 'Dermatology'),
(183, 'Retinal Laser Therapy', 'Laser treatment for retinal tears or diabetic retinopathy', 'Ophthalmology'),
(184, 'Eye Trauma Repair', 'Surgical repair of ocular injuries', 'Ophthalmology'),
(185, 'Glaucoma Drainage Implant', 'Insertion of drainage device to lower eye pressure', 'Ophthalmology'),
(186, 'Corneal Cross-Linking', 'Strengthening of corneal tissue for keratoconus', 'Ophthalmology'),
(187, 'Ocular Ultrasound', 'Ultrasound imaging of eye structures', 'Ophthalmology'),
(188, 'Endoscopic Sinus Surgery', 'Minimally invasive removal of sinus blockages', 'ENT'),
(189, 'Tonsillectomy Revision', 'Secondary removal or correction of tonsil tissue', 'ENT'),
(190, 'Voice Cord Polyp Removal', 'Surgical excision of vocal cord polyps', 'ENT'),
(191, 'Endoscopic Sinus Surgery', 'Minimally invasive sinus procedure', 'ENT'),
(192, 'Coronary Stent Placement', 'Insertion of stent to keep artery open', 'Cardiology'),
(193, 'Liver Transplant', 'Surgical replacement of diseased liver', 'Gastroenterology'),
(194, 'Bone Marrow Aspiration', 'Extraction of marrow for testing', 'Oncology'),
(195, 'Thoracic Surgery', 'Surgical procedure on chest organs', 'Respiratory'),
(196, 'Endoscopy', 'Flexible tube examination of digestive tract', 'Gastroenterology'),
(197, 'Colonoscopy', 'Endoscopic examination of colon', 'Gastroenterology'),
(198, 'Gastrectomy', 'Surgical removal of part of stomach', 'Gastroenterology'),
(199, 'Polypectomy', 'Removal of polyps from colon', 'Gastroenterology'),
(200, 'Liver Biopsy', 'Tissue sampling from liver for diagnosis', 'Gastroenterology');

