INSERT INTO Admission_Diagnosis 
( Admission_Diagnosis_ID,  Diagnosis_Type,Diagnosis_Category, Severity_Level)
VALUES
(1, 'Inpatient', 'Cardiology', 'Moderate'),
(2, 'Inpatient', 'Cardiology', 'Severe'),
(3, 'Inpatient', 'Cardiology', 'Critical'),
(4, 'Outpatient', 'Cardiology', 'Mild'),
(5, 'Emergency', 'Cardiology', 'Critical'),
(6, 'Inpatient', 'Oncology', 'Moderate'),
(7, 'Inpatient', 'Oncology', 'Severe'),
(8, 'Outpatient', 'Oncology', 'Mild'),
(9, 'Emergency', 'Oncology', 'Critical'),
(10, 'Inpatient', 'Oncology', 'Critical'),
(11, 'Inpatient', 'Neurology', 'Moderate'),
(12, 'Inpatient', 'Neurology', 'Severe'),
(13, 'Outpatient', 'Neurology', 'Mild'),
(14, 'Emergency', 'Neurology', 'Critical'),
(15, 'Inpatient', 'Neurology', 'Critical'),
(16, 'Inpatient', 'Orthopedics', 'Moderate'),
(17, 'Inpatient', 'Orthopedics', 'Severe'),
(18, 'Outpatient', 'Orthopedics', 'Mild'),
(19, 'Emergency', 'Orthopedics', 'Critical'),
(20, 'Inpatient', 'Orthopedics', 'Critical'),
(21, 'Inpatient', 'Pediatrics', 'Moderate'),
(22, 'Inpatient', 'Pediatrics', 'Severe'),
(23, 'Outpatient', 'Pediatrics', 'Mild'),
(24, 'Emergency', 'Pediatrics', 'Critical'),
(25, 'Inpatient', 'Pediatrics', 'Critical'),
(26, 'Inpatient', 'General Medicine', 'Moderate'),
(27, 'Inpatient', 'General Medicine', 'Severe'),
(28, 'Outpatient', 'General Medicine', 'Mild'),
(29, 'Emergency', 'General Medicine', 'Critical'),
(30, 'Inpatient', 'General Medicine', 'Critical'),
(31, 'Inpatient', 'Maternity', 'Moderate'),
(32, 'Inpatient', 'Maternity', 'Severe'),
(33, 'Outpatient', 'Maternity', 'Mild'),
(34, 'Emergency', 'Maternity', 'Critical'),
(35, 'Inpatient', 'Maternity', 'Critical'),
(36, 'Inpatient', 'ICU', 'Moderate'),
(37, 'Inpatient', 'ICU', 'Severe'),
(38, 'Emergency', 'ICU', 'Critical'),
(39, 'Inpatient', 'ICU', 'Critical'),
(40, 'Outpatient', 'ICU', 'Mild'),
(41, 'Outpatient', 'Orthopedics', 'Mild'),
(42, 'Outpatient', 'Orthopedics', 'Moderate'),
(43, 'Outpatient', 'Orthopedics', 'Severe'),
(44, 'Outpatient', 'Orthopedics', 'Critical'),
(45, 'Emergency', 'Orthopedics', 'Mild'),
(46, 'Emergency', 'Orthopedics', 'Moderate'),
(47, 'Emergency', 'Orthopedics', 'Severe'),
(48, 'Emergency', 'Orthopedics', 'Critical'),

(49, 'Inpatient', 'Pediatrics', 'Mild'),
(50, 'Inpatient', 'Pediatrics', 'Moderate'),
(51, 'Inpatient', 'Pediatrics', 'Severe'),
(52, 'Inpatient', 'Pediatrics', 'Critical'),
(53, 'Outpatient', 'Pediatrics', 'Mild'),
(54, 'Outpatient', 'Pediatrics', 'Moderate'),
(55, 'Outpatient', 'Pediatrics', 'Severe'),
(56, 'Outpatient', 'Pediatrics', 'Critical'),
(57, 'Emergency', 'Pediatrics', 'Mild'),
(58, 'Emergency', 'Pediatrics', 'Moderate'),
(59, 'Emergency', 'Pediatrics', 'Severe'),
(60, 'Emergency', 'Pediatrics', 'Critical'),

(61, 'Inpatient', 'General Medicine', 'Mild'),
(62, 'Inpatient', 'General Medicine', 'Moderate'),
(63, 'Inpatient', 'General Medicine', 'Severe'),
(64, 'Inpatient', 'General Medicine', 'Critical'),
(65, 'Outpatient', 'General Medicine', 'Mild'),
(66, 'Outpatient', 'General Medicine', 'Moderate'),
(67, 'Outpatient', 'General Medicine', 'Severe'),
(68, 'Outpatient', 'General Medicine', 'Critical'),
(69, 'Emergency', 'General Medicine', 'Mild'),
(70, 'Emergency', 'General Medicine', 'Moderate'),
(71, 'Emergency', 'General Medicine', 'Severe'),
(72, 'Emergency', 'General Medicine', 'Critical'),

(73, 'Inpatient', 'Maternity', 'Mild'),
(74, 'Inpatient', 'Maternity', 'Moderate'),
(75, 'Inpatient', 'Maternity', 'Severe'),
(76, 'Inpatient', 'Maternity', 'Critical'),
(77, 'Outpatient', 'Maternity', 'Mild'),
(78, 'Outpatient', 'Maternity', 'Moderate'),
(79, 'Outpatient', 'Maternity', 'Severe'),
(80, 'Outpatient', 'Maternity', 'Critical'),
(81, 'Emergency', 'Maternity', 'Mild'),
(82, 'Emergency', 'Maternity', 'Moderate'),
(83, 'Emergency', 'Maternity', 'Severe'),
(84, 'Emergency', 'Maternity', 'Critical'),
(85, 'Inpatient', 'ICU', 'Mild'),
(86, 'Inpatient', 'ICU', 'Moderate'),
(87, 'Inpatient', 'ICU', 'Severe'),
(88, 'Inpatient', 'ICU', 'Critical'),
(89, 'Outpatient', 'ICU', 'Mild'),
(90, 'Outpatient', 'ICU', 'Moderate'),
(91, 'Outpatient', 'ICU', 'Severe'),
(92, 'Outpatient', 'ICU', 'Critical'),
(93, 'Emergency', 'ICU', 'Mild'),
(94, 'Emergency', 'ICU', 'Moderate'),
(95, 'Emergency', 'ICU', 'Severe'),
(96, 'Emergency', 'ICU', 'Critical'),
(97, 'Inpatient', 'Surgical', 'Mild'),
(98, 'Inpatient', 'Surgical', 'Moderate'),
(99, 'Inpatient', 'Surgical', 'Severe'),
(100, 'Inpatient', 'Surgical', 'Critical'),
(101, 'Outpatient', 'Surgical', 'Mild'),
(102, 'Outpatient', 'Surgical', 'Moderate'),
(103, 'Outpatient', 'Surgical', 'Severe'),
(104, 'Outpatient', 'Surgical', 'Critical'),
(105, 'Emergency', 'Surgical', 'Mild'),
(106, 'Emergency', 'Surgical', 'Moderate'),
(107, 'Emergency', 'Surgical', 'Severe'),
(108, 'Emergency', 'Surgical', 'Critical'),
(109, 'Inpatient', 'Respiratory', 'Mild'),
(110, 'Inpatient', 'Respiratory', 'Moderate'),
(111, 'Inpatient', 'Respiratory', 'Severe'),
(112, 'Inpatient', 'Respiratory', 'Critical'),
(113, 'Outpatient', 'Respiratory', 'Mild'),
(114, 'Outpatient', 'Respiratory', 'Moderate'),
(115, 'Outpatient', 'Respiratory', 'Severe'),
(116, 'Outpatient', 'Respiratory', 'Critical'),
(117, 'Emergency', 'Respiratory', 'Mild'),
(118, 'Emergency', 'Respiratory', 'Moderate'),
(119, 'Emergency', 'Respiratory', 'Severe'),
(120, 'Emergency', 'Respiratory', 'Critical'),
(121, 'Inpatient', 'Cardiology', 'Mild'),
(122, 'Inpatient', 'Cardiology', 'Moderate'),
(123, 'Inpatient', 'Cardiology', 'Severe'),
(124, 'Inpatient', 'Cardiology', 'Critical'),
(125, 'Outpatient', 'Cardiology', 'Mild'),
(126, 'Outpatient', 'Cardiology', 'Moderate'),
(127, 'Outpatient', 'Cardiology', 'Severe'),
(128, 'Outpatient', 'Cardiology', 'Critical'),
(129, 'Emergency', 'Cardiology', 'Mild'),
(130, 'Emergency', 'Cardiology', 'Moderate'),
(131, 'Emergency', 'Cardiology', 'Severe'),
(132, 'Emergency', 'Cardiology', 'Critical'),
(133, 'Inpatient', 'Oncology', 'Mild'),
(134, 'Inpatient', 'Oncology', 'Moderate'),
(135, 'Inpatient', 'Oncology', 'Severe'),
(136, 'Inpatient', 'Oncology', 'Critical'),
(137, 'Outpatient', 'Oncology', 'Mild'),
(138, 'Outpatient', 'Oncology', 'Moderate'),
(139, 'Outpatient', 'Oncology', 'Severe'),
(140, 'Outpatient', 'Oncology', 'Critical'),
(141, 'Emergency', 'Oncology', 'Mild'),
(142, 'Emergency', 'Oncology', 'Moderate'),
(143, 'Emergency', 'Oncology', 'Severe'),
(144, 'Emergency', 'Oncology', 'Critical'),
(145, 'Inpatient', 'Neurology', 'Mild'),
(146, 'Inpatient', 'Neurology', 'Moderate'),
(147, 'Inpatient', 'Neurology', 'Severe'),
(148, 'Inpatient', 'Neurology', 'Critical'),
(149, 'Outpatient', 'Neurology', 'Mild'),
(150, 'Outpatient', 'Neurology', 'Moderate'),
(151, 'Outpatient', 'Neurology', 'Severe'),
(152, 'Outpatient', 'Neurology', 'Critical'),
(153, 'Emergency', 'Neurology', 'Mild'),
(154, 'Emergency', 'Neurology', 'Moderate'),
(155, 'Emergency', 'Neurology', 'Severe'),
(156, 'Emergency', 'Neurology', 'Critical'),
(157, 'Inpatient', 'Orthopedics', 'Mild'),
(158, 'Inpatient', 'Orthopedics', 'Moderate'),
(159, 'Inpatient', 'Orthopedics', 'Severe'),
(160, 'Inpatient', 'Orthopedics', 'Critical'),
(161, 'Outpatient', 'Orthopedics', 'Mild'),
(162, 'Outpatient', 'Orthopedics', 'Moderate'),
(163, 'Outpatient', 'Orthopedics', 'Severe'),
(164, 'Outpatient', 'Orthopedics', 'Critical'),
(165, 'Emergency', 'Orthopedics', 'Mild'),
(166, 'Emergency', 'Orthopedics', 'Moderate'),
(167, 'Emergency', 'Orthopedics', 'Severe'),
(168, 'Emergency', 'Orthopedics', 'Critical'),
(169, 'Inpatient', 'Pediatrics', 'Mild'),
(170, 'Inpatient', 'Pediatrics', 'Moderate'),
(171, 'Inpatient', 'Pediatrics', 'Severe'),
(172, 'Inpatient', 'Pediatrics', 'Critical'),
(173, 'Outpatient', 'Pediatrics', 'Mild'),
(174, 'Outpatient', 'Pediatrics', 'Moderate'),
(175, 'Outpatient', 'Pediatrics', 'Severe'),
(176, 'Outpatient', 'Pediatrics', 'Critical'),
(177, 'Emergency', 'Pediatrics', 'Mild'),
(178, 'Emergency', 'Pediatrics', 'Moderate'),
(179, 'Emergency', 'Pediatrics', 'Severe'),
(180, 'Emergency', 'Pediatrics', 'Critical'),
(181, 'Inpatient', 'General Medicine', 'Mild'),
(182, 'Inpatient', 'General Medicine', 'Moderate'),
(183, 'Inpatient', 'General Medicine', 'Severe'),
(184, 'Inpatient', 'General Medicine', 'Critical'),
(185, 'Outpatient', 'General Medicine', 'Mild'),
(186, 'Outpatient', 'General Medicine', 'Moderate'),
(187, 'Outpatient', 'General Medicine', 'Severe'),
(188, 'Outpatient', 'General Medicine', 'Critical'),
(189, 'Emergency', 'General Medicine', 'Mild'),
(190, 'Emergency', 'General Medicine', 'Moderate'),
(191, 'Emergency', 'General Medicine', 'Severe'),
(192, 'Emergency', 'General Medicine', 'Critical'),
(193, 'Inpatient', 'Respiratory', 'Mild'),
(194, 'Inpatient', 'Respiratory', 'Moderate'),
(195, 'Inpatient', 'Respiratory', 'Severe'),
(196, 'Inpatient', 'Respiratory', 'Critical'),
(197, 'Outpatient', 'Respiratory', 'Mild'),
(198, 'Outpatient', 'Respiratory', 'Moderate'),
(199, 'Outpatient', 'Respiratory', 'Severe'),
(200, 'Outpatient', 'Respiratory', 'Critical');


 