INSERT INTO  Dim_Bed_Type
( Bed_Type_ID,Bed_Type_Classification )
VALUES
(1, 'General Ward Bed'),
(2, 'Semi-Private Ward Bed'),
(3, 'Private Ward Bed'),
(4, 'ICU Bed'),
(5, 'High Care Bed'),
(6, 'Step-Down Unit Bed'),
(7, 'Pediatric Ward Bed'),
(8, 'Neonatal ICU Bed'),
(9, 'Maternity Ward Bed'),
(10, 'Delivery Suite Bed'),
(11, 'Postnatal Recovery Bed'),
(12, 'Surgical Ward Bed'),
(13, 'Orthopedic Ward Bed'),
(14, 'Cardiology Ward Bed'),
(15, 'Oncology Ward Bed'),
(16, 'Neurology Ward Bed'),
(17, 'Psychiatric Ward Bed'),
(18, 'Rehabilitation Bed'),
(19, 'Day Ward Bed'),
(20, 'Outpatient Procedure Bed'),
(21, 'Emergency Unit Bed'),
(22, 'Trauma Unit Bed'),
(23, 'Burn Unit Bed'),
(24, 'Isolation Ward Bed'),
(25, 'Infectious Disease Bed'),
(26, 'Respiratory Ward Bed'),
(27, 'Renal Unit Bed'),
(28, 'Dialysis Chair'),
(29, 'Cardiac ICU Bed'),
(30, 'Surgical ICU Bed'),
(31, 'Medical ICU Bed'),
(32, 'High Dependency Bed'),
(33, 'Observation Bed'),
(34, 'Short-Stay Bed'),
(35, 'Long-Term Care Bed'),
(36, 'Geriatric Ward Bed'),
(37, 'Palliative Care Bed'),
(38, 'Hospice Bed'),
(39, 'Chemotherapy Recliner'),
(40, 'Radiology Recovery Bed'),
(41, 'Cath Lab Recovery Bed'),
(42, 'Endoscopy Recovery Bed'),
(43, 'Procedure Room Bed'),
(44, 'Operating Theatre Table'),
(45, 'Post-Anesthesia Care Bed'),
(46, 'Day Surgery Bed'),
(47, 'Minor Procedure Bed'),
(48, 'ENT Ward Bed'),
(49, 'Ophthalmology Ward Bed'),
(50, 'Dermatology Ward Bed'),
(51, 'General Ward Bed'),
(52, 'Semi-Private Ward Bed'),
(53, 'Long-Term Care Bed'),
(54, 'Geriatric Ward Bed'),
(55, 'Palliative Care Bed'),
(56, 'Hospice Bed'),
(57, 'Chemotherapy Recliner'),
(58, 'Radiology Recovery Bed'),
(59, 'Cath Lab Recovery Bed'),
(60, 'Endoscopy Recovery Bed'),
(61, 'Procedure Room Bed'),
(62, 'Operating Theatre Table'),
(63, 'Post-Anesthesia Care Bed'),
(64, 'Day Surgery Bed'),
(65, 'Minor Procedure Bed'),
(66, 'ENT Ward Bed'),
(67, 'Ophthalmology Ward Bed'),
(68, 'Dermatology Ward Bed'),
(69, 'General Ward Bed'),
(70, 'Semi-Private Ward Bed'),
(71, 'Private Ward Bed'),
(72, 'ICU Bed'),
(73, 'High Care Bed'),
(74, 'Step-Down Unit Bed'),
(75, 'Pediatric Ward Bed'),
(76, 'Neonatal ICU Bed'),
(77, 'Maternity Ward Bed'),
(78, 'Delivery Suite Bed'),
(79, 'Postnatal Recovery Bed'),
(80, 'Surgical Ward Bed'),
(81, 'Orthopedic Ward Bed'),
(82, 'Cardiology Ward Bed'),
(83, 'Oncology Ward Bed'),
(84, 'Neurology Ward Bed'),
(85, 'Psychiatric Ward Bed'),
(86, 'Rehabilitation Bed'),
(87, 'Day Ward Bed'),
(88, 'Outpatient Procedure Bed'),
(89, 'Emergency Unit Bed'),
(90, 'Trauma Unit Bed'),
(91, 'Burn Unit Bed'),
(92, 'Isolation Ward Bed'),
(93, 'Infectious Disease Bed'),
(94, 'Respiratory Ward Bed'),
(95, 'Renal Unit Bed'),
(96, 'Dialysis Chair'),
(97, 'Cardiac ICU Bed'),
(98, 'Surgical ICU Bed'),
(99, 'Medical ICU Bed'),
(100, 'High Dependency Bed'),
(101, 'Observation Bed'),
(102, 'Short-Stay Bed'),
(103, 'Long-Term Care Bed'),
(104, 'Geriatric Ward Bed'),
(105, 'Palliative Care Bed'),
(106, 'Hospice Bed'),
(107, 'Chemotherapy Recliner'),
(108, 'Radiology Recovery Bed'),
(109, 'Cath Lab Recovery Bed'),
(110, 'Endoscopy Recovery Bed'),
(111, 'Procedure Room Bed'),
(112, 'Operating Theatre Table'),
(113, 'Post-Anesthesia Care Bed'),
(114, 'Day Surgery Bed'),
(115, 'Minor Procedure Bed'),
(116, 'ENT Ward Bed'),
(117, 'Ophthalmology Ward Bed'),
(118, 'Dermatology Ward Bed'),
(119, 'General Ward Bed'),
(120, 'Semi-Private Ward Bed'),
(121, 'Private Ward Bed'),
(122, 'ICU Bed'),
(123, 'High Care Bed'),
(124, 'Step-Down Unit Bed'),
(125, 'Pediatric Ward Bed'),
(126, 'Neonatal ICU Bed'),
(127, 'Maternity Ward Bed'),
(128, 'Delivery Suite Bed'),
(129, 'Postnatal Recovery Bed'),
(130, 'Surgical Ward Bed'),
(131, 'Orthopedic Ward Bed'),
(132, 'Cardiology Ward Bed'),
(133, 'Oncology Ward Bed'),
(134, 'Neurology Ward Bed'),
(135, 'Psychiatric Ward Bed'),
(136, 'Rehabilitation Bed'),
(137, 'Day Ward Bed'),
(138, 'Outpatient Procedure Bed'),
(139, 'Emergency Unit Bed'),
(140, 'Trauma Unit Bed'),
(141, 'Burn Unit Bed'),
(142, 'Isolation Ward Bed'),
(143, 'Infectious Disease Bed'),
(144, 'Respiratory Ward Bed'),
(145, 'Renal Unit Bed'),
(146, 'Dialysis Chair'),
(147, 'Cardiac ICU Bed'),
(148, 'Surgical ICU Bed'),
(149, 'Medical ICU Bed'),
(150, 'High Dependency Bed'),
(151, 'Observation Bed'),
(152, 'Short-Stay Bed'),
(153, 'Long-Term Care Bed'),
(154, 'Geriatric Ward Bed'),
(155, 'Palliative Care Bed'),
(156, 'Hospice Bed'),
(157, 'Chemotherapy Recliner'),
(158, 'Radiology Recovery Bed'),
(159, 'Cath Lab Recovery Bed'),
(160, 'Endoscopy Recovery Bed'),
(161, 'Procedure Room Bed'),
(162, 'Operating Theatre Table'),
(163, 'Post-Anesthesia Care Bed'),
(164, 'Day Surgery Bed'),
(165, 'Minor Procedure Bed'),
(166, 'ENT Ward Bed'),
(167, 'Ophthalmology Ward Bed'),
(168, 'Dermatology Ward Bed'),
(169, 'General Ward Bed'),
(170, 'Semi-Private Ward Bed'),
(171, 'Private Ward Bed'),
(172, 'ICU Bed'),
(173, 'High Care Bed'),
(174, 'Step-Down Unit Bed'),
(175, 'Pediatric Ward Bed'),
(176, 'Neonatal ICU Bed'),
(177, 'Maternity Ward Bed'),
(178, 'Delivery Suite Bed'),
(179, 'Postnatal Recovery Bed'),
(180, 'Surgical Ward Bed'),
(181, 'Orthopedic Ward Bed'),
(182, 'Cardiology Ward Bed'),
(183, 'Oncology Ward Bed'),
(184, 'Neurology Ward Bed'),
(185, 'Psychiatric Ward Bed'),
(186, 'Rehabilitation Bed'),
(187, 'Day Ward Bed'),
(188, 'Outpatient Procedure Bed'),
(189, 'Emergency Unit Bed'),
(190, 'Isolation Ward Bed'),
(191, 'Infectious Disease Bed'),
(192, 'Respiratory Ward Bed'),
(193, 'Renal Unit Bed'),
(194, 'Dialysis Chair'),
(195, 'Cardiac ICU Bed'),
(196, 'Surgical ICU Bed'),
(197, 'Medical ICU Bed'),
(198, 'High Dependency Bed'),
(199, 'Observation Bed'),
(200, 'Short-Stay Bed');