INSERT INTO Dim_location 
( Location_ID,  Hospital,  Region, Ward )
VALUES 
(1, 'Life Fourways Hospital', 'Gauteng', 'Cardiology'),
(2, 'Life Fourways Hospital', 'Gauteng', 'Oncology'),
(3, 'Life Fourways Hospital', 'Gauteng', 'Pediatrics'),
(4, 'Life Fourways Hospital', 'Gauteng', 'ICU'),
(5, 'Life Fourways Hospital', 'Gauteng', 'Emergency'),
(6, 'Life Brenthurst Hospital', 'Gauteng', 'Cardiology'),
(7, 'Life Brenthurst Hospital', 'Gauteng', 'Oncology'),
(8, 'Life Brenthurst Hospital', 'Gauteng', 'Neurology'),
(9, 'Life Brenthurst Hospital', 'Gauteng', 'Orthopedics'),
(10, 'Life Brenthurst Hospital', 'Gauteng', 'General Medicine'),
(11, 'Life Wilgers Hospital', 'Gauteng', 'Maternity'),
(12, 'Life Wilgers Hospital', 'Gauteng', 'ICU'),
(13, 'Life Wilgers Hospital', 'Gauteng', 'Emergency'),
(14, 'Life Wilgers Hospital', 'Gauteng', 'Surgical'),
(15, 'Life Wilgers Hospital', 'Gauteng', 'Pediatrics'),
(16, 'Life Eugene Marais Hospital', 'Gauteng', 'Cardiology'),
(17, 'Life Eugene Marais Hospital', 'Gauteng', 'Oncology'),
(18, 'Life Eugene Marais Hospital', 'Gauteng', 'Neurology'),
(19, 'Life Eugene Marais Hospital', 'Gauteng', 'Orthopedics'),
(20, 'Life Eugene Marais Hospital', 'Gauteng', 'General Medicine'),
(21, 'Life Vincent Pallotti Hospital', 'Western Cape', 'Cardiology'),
(22, 'Life Vincent Pallotti Hospital', 'Western Cape', 'Oncology'),
(23, 'Life Vincent Pallotti Hospital', 'Western Cape', 'Neurology'),
(24, 'Life Vincent Pallotti Hospital', 'Western Cape', 'Orthopedics'),
(25, 'Life Vincent Pallotti Hospital', 'Western Cape', 'General Medicine'),
(26, 'Life Kingsbury Hospital', 'Western Cape', 'ICU'),
(27, 'Life Kingsbury Hospital', 'Western Cape', 'Emergency'),
(28, 'Life Kingsbury Hospital', 'Western Cape', 'Surgical'),
(29, 'Life Kingsbury Hospital', 'Western Cape', 'Maternity'),
(30, 'Life Kingsbury Hospital', 'Western Cape', 'Pediatrics'),
(31, 'Life Westville Hospital', 'KwaZulu-Natal', 'Cardiology'),
(32, 'Life Westville Hospital', 'KwaZulu-Natal', 'Oncology'),
(33, 'Life Westville Hospital', 'KwaZulu-Natal', 'Neurology'),
(34, 'Life Westville Hospital', 'KwaZulu-Natal', 'Orthopedics'),
(35, 'Life Westville Hospital', 'KwaZulu-Natal', 'General Medicine'),
(36, 'Life Entabeni Hospital', 'KwaZulu-Natal', 'ICU'),
(37, 'Life Entabeni Hospital', 'KwaZulu-Natal', 'Emergency'),
(38, 'Life Entabeni Hospital', 'KwaZulu-Natal', 'Surgical'),
(39, 'Life Entabeni Hospital', 'KwaZulu-Natal', 'Maternity'),
(40, 'Life Entabeni Hospital', 'KwaZulu-Natal', 'Pediatrics'),
(41, 'Life Rosepark Hospital', 'Free State', 'Cardiology'),
(42, 'Life Rosepark Hospital', 'Free State', 'Oncology'),
(43, 'Life Rosepark Hospital', 'Free State', 'Neurology'),
(44, 'Life Rosepark Hospital', 'Free State', 'Orthopedics'),
(45, 'Life Rosepark Hospital', 'Free State', 'General Medicine'),
(46, 'Life Pasteur Hospital', 'Free State', 'ICU'),
(47, 'Life Pasteur Hospital', 'Free State', 'Emergency'),
(48, 'Life Pasteur Hospital', 'Free State', 'Surgical'),
(49, 'Life Pasteur Hospital', 'Free State', 'Maternity'),
(50, 'Life Pasteur Hospital', 'Free State', 'Pediatrics'),
(51, 'Life Peglerae Hospital', 'North West', 'Cardiology'),
(52, 'Life Peglerae Hospital', 'North West', 'Oncology'),
(53, 'Life Peglerae Hospital', 'North West', 'Neurology'),
(54, 'Life Peglerae Hospital', 'North West', 'Orthopedics'),
(55, 'Life Peglerae Hospital', 'North West', 'General Medicine'),
(56, 'Life Anncron Hospital', 'North West', 'ICU'),
(57, 'Life Anncron Hospital', 'North West', 'Emergency'),
(58, 'Life Anncron Hospital', 'North West', 'Surgical'),
(59, 'Life Anncron Hospital', 'North West', 'Maternity'),
(60, 'Life Anncron Hospital', 'North West', 'Pediatrics'),
(61, 'Life St Dominic’s Hospital', 'Eastern Cape', 'Cardiology'),
(62, 'Life St Dominic’s Hospital', 'Eastern Cape', 'Oncology'),
(63, 'Life St Dominic’s Hospital', 'Eastern Cape', 'Neurology'),
(64, 'Life St Dominic’s Hospital', 'Eastern Cape', 'Orthopedics'),
(65, 'Life St Dominic’s Hospital', 'Eastern Cape', 'General Medicine'),
(66, 'Life Beacon Bay Hospital', 'Eastern Cape', 'ICU'),
(67, 'Life Beacon Bay Hospital', 'Eastern Cape', 'Emergency'),
(68, 'Life Beacon Bay Hospital', 'Eastern Cape', 'Surgical'),
(69, 'Life Beacon Bay Hospital', 'Eastern Cape', 'Maternity'),
(70, 'Life Beacon Bay Hospital', 'Eastern Cape', 'Pediatrics'),
(71, 'Life Bay View Hospital', 'Western Cape', 'Cardiology'),
(72, 'Life Bay View Hospital', 'Western Cape', 'Oncology'),
(73, 'Life Bay View Hospital', 'Western Cape', 'Neurology'),
(74, 'Life Bay View Hospital', 'Western Cape', 'Orthopedics'),
(75, 'Life Bay View Hospital', 'Western Cape', 'General Medicine'),
(76, 'Life Knysna Hospital', 'Western Cape', 'ICU'),
(77, 'Life Knysna Hospital', 'Western Cape', 'Emergency'),
(78, 'Life Knysna Hospital', 'Western Cape', 'Surgical'),
(79, 'Life Knysna Hospital', 'Western Cape', 'Maternity'),
(80, 'Life Knysna Hospital', 'Western Cape', 'Pediatrics'),
(81, 'Life Bay View Hospital', 'Western Cape', 'ICU'),
(82, 'Life Bay View Hospital', 'Western Cape', 'Emergency'),
(83, 'Life Bay View Hospital', 'Western Cape', 'Surgical'),
(84, 'Life Bay View Hospital', 'Western Cape', 'Maternity'),
(85, 'Life Bay View Hospital', 'Western Cape', 'Pediatrics'),
(86, 'Life Knysna Hospital', 'Western Cape', 'Cardiology'),
(87, 'Life Knysna Hospital', 'Western Cape', 'Oncology'),
(88, 'Life Knysna Hospital', 'Western Cape', 'Neurology'),
(89, 'Life Knysna Hospital', 'Western Cape', 'Orthopedics'),
(90, 'Life Knysna Hospital', 'Western Cape', 'General Medicine'),
(91, 'Life Midmed Hospital', 'Mpumalanga', 'ICU'),
(92, 'Life Midmed Hospital', 'Mpumalanga', 'Emergency'),
(93, 'Life Midmed Hospital', 'Mpumalanga', 'Surgical'),
(94, 'Life Midmed Hospital', 'Mpumalanga', 'Maternity'),
(95, 'Life Midmed Hospital', 'Mpumalanga', 'Pediatrics'),
(96, 'Life Cosmos Hospital', 'Mpumalanga', 'Cardiology'),
(97, 'Life Cosmos Hospital', 'Mpumalanga', 'Oncology'),
(98, 'Life Cosmos Hospital', 'Mpumalanga', 'Neurology'),
(99, 'Life Cosmos Hospital', 'Mpumalanga', 'Orthopedics'),
(100, 'Life Cosmos Hospital', 'Mpumalanga', 'General Medicine'),
(101, 'Life Piet Retief Hospital', 'Mpumalanga', 'ICU'),
(102, 'Life Piet Retief Hospital', 'Mpumalanga', 'Emergency'),
(103, 'Life Piet Retief Hospital', 'Mpumalanga', 'Surgical'),
(104, 'Life Piet Retief Hospital', 'Mpumalanga', 'Maternity'),
(105, 'Life Piet Retief Hospital', 'Mpumalanga', 'Pediatrics'),
(106, 'Life Suikerbosrand Hospital', 'Gauteng', 'Cardiology'),
(107, 'Life Suikerbosrand Hospital', 'Gauteng', 'Oncology'),
(108, 'Life Suikerbosrand Hospital', 'Gauteng', 'Neurology'),
(109, 'Life Suikerbosrand Hospital', 'Gauteng', 'Orthopedics'),
(110, 'Life Suikerbosrand Hospital', 'Gauteng', 'General Medicine'),
(111, 'Life Carstenhof Hospital', 'Gauteng', 'ICU'),
(112, 'Life Carstenhof Hospital', 'Gauteng', 'Emergency'),
(113, 'Life Carstenhof Hospital', 'Gauteng', 'Surgical'),
(114, 'Life Carstenhof Hospital', 'Gauteng', 'Maternity'),
(115, 'Life Carstenhof Hospital', 'Gauteng', 'Pediatrics'),
(116, 'Life Glynnwood Hospital', 'Gauteng', 'Cardiology'),
(117, 'Life Glynnwood Hospital', 'Gauteng', 'Oncology'),
(118, 'Life Glynnwood Hospital', 'Gauteng', 'Neurology'),
(119, 'Life Glynnwood Hospital', 'Gauteng', 'Orthopedics'),
(120, 'Life Glynnwood Hospital', 'Gauteng', 'General Medicine'),
(121, 'Life Robinson Hospital', 'Gauteng', 'ICU'),
(122, 'Life Robinson Hospital', 'Gauteng', 'Emergency'),
(123, 'Life Robinson Hospital', 'Gauteng', 'Surgical'),
(124, 'Life Robinson Hospital', 'Gauteng', 'Maternity'),
(125, 'Life Robinson Hospital', 'Gauteng', 'Pediatrics'),
(126, 'Life Flora Hospital', 'Gauteng', 'Cardiology'),
(127, 'Life Flora Hospital', 'Gauteng', 'Oncology'),
(128, 'Life Flora Hospital', 'Gauteng', 'Neurology'),
(129, 'Life Flora Hospital', 'Gauteng', 'Orthopedics'),
(130, 'Life Flora Hospital', 'Gauteng', 'General Medicine'),
(131, 'Life Groenkloof Hospital', 'Gauteng', 'ICU'),
(132, 'Life Groenkloof Hospital', 'Gauteng', 'Emergency'),
(133, 'Life Groenkloof Hospital', 'Gauteng', 'Surgical'),
(134, 'Life Groenkloof Hospital', 'Gauteng', 'Maternity'),
(135, 'Life Groenkloof Hospital', 'Gauteng', 'Pediatrics'),
(136, 'Life Springs Parkland Hospital', 'Gauteng', 'Cardiology'),
(137, 'Life Springs Parkland Hospital', 'Gauteng', 'Oncology'),
(138, 'Life Springs Parkland Hospital', 'Gauteng', 'Neurology'),
(139, 'Life Springs Parkland Hospital', 'Gauteng', 'Orthopedics'),
(140, 'Life Springs Parkland Hospital', 'Gauteng', 'General Medicine'),
(141, 'Life East London Private Hospital', 'Eastern Cape', 'ICU'),
(142, 'Life East London Private Hospital', 'Eastern Cape', 'Emergency'),
(143, 'Life East London Private Hospital', 'Eastern Cape', 'Surgical'),
(144, 'Life East London Private Hospital', 'Eastern Cape', 'Maternity'),
(145, 'Life East London Private Hospital', 'Eastern Cape', 'Pediatrics'),
(146, 'Life Mercantile Hospital', 'Eastern Cape', 'Cardiology'),
(147, 'Life Mercantile Hospital', 'Eastern Cape', 'Oncology'),
(148, 'Life Mercantile Hospital', 'Eastern Cape', 'Neurology'),
(149, 'Life Mercantile Hospital', 'Eastern Cape', 'Orthopedics'),
(150, 'Life Mercantile Hospital', 'Eastern Cape', 'General Medicine'),
(151, 'Life Mercantile Hospital', 'Eastern Cape', 'ICU'),
(152, 'Life Mercantile Hospital', 'Eastern Cape', 'Emergency'),
(153, 'Life Mercantile Hospital', 'Eastern Cape', 'Surgical'),
(154, 'Life Mercantile Hospital', 'Eastern Cape', 'Maternity'),
(155, 'Life Mercantile Hospital', 'Eastern Cape', 'Pediatrics'),
(156, 'Life Hilton Private Hospital', 'KwaZulu-Natal', 'Cardiology'),
(157, 'Life Hilton Private Hospital', 'KwaZulu-Natal', 'Oncology'),
(158, 'Life Hilton Private Hospital', 'KwaZulu-Natal', 'Neurology'),
(159, 'Life Hilton Private Hospital', 'KwaZulu-Natal', 'Orthopedics'),
(160, 'Life Hilton Private Hospital', 'KwaZulu-Natal', 'General Medicine'),
(161, 'Life Mount Edgecombe Hospital', 'KwaZulu-Natal', 'ICU'),
(162, 'Life Mount Edgecombe Hospital', 'KwaZulu-Natal', 'Emergency'),
(163, 'Life Mount Edgecombe Hospital', 'KwaZulu-Natal', 'Surgical'),
(164, 'Life Mount Edgecombe Hospital', 'KwaZulu-Natal', 'Maternity'),
(165, 'Life Mount Edgecombe Hospital', 'KwaZulu-Natal', 'Pediatrics'),
(166, 'Life Empangeni Hospital', 'KwaZulu-Natal', 'Cardiology'),
(167, 'Life Empangeni Hospital', 'KwaZulu-Natal', 'Oncology'),
(168, 'Life Empangeni Hospital', 'KwaZulu-Natal', 'Neurology'),
(169, 'Life Empangeni Hospital', 'KwaZulu-Natal', 'Orthopedics'),
(170, 'Life Empangeni Hospital', 'KwaZulu-Natal', 'General Medicine'),
(171, 'Life Anncron Hospital', 'North West', 'Cardiology'),
(172, 'Life Anncron Hospital', 'North West', 'Oncology'),
(173, 'Life Anncron Hospital', 'North West', 'Neurology'),
(174, 'Life Anncron Hospital', 'North West', 'Orthopedics'),
(175, 'Life Anncron Hospital', 'North West', 'General Medicine'),
(176, 'Life Peglerae Hospital', 'North West', 'ICU'),
(177, 'Life Peglerae Hospital', 'North West', 'Emergency'),
(178, 'Life Peglerae Hospital', 'North West', 'Surgical'),
(179, 'Life Peglerae Hospital', 'North West', 'Maternity'),
(180, 'Life Peglerae Hospital', 'North West', 'Pediatrics'),
(181, 'Life St Mary’s Hospital', 'KwaZulu-Natal', 'Cardiology'),
(182, 'Life St Mary’s Hospital', 'KwaZulu-Natal', 'Oncology'),
(183, 'Life St Mary’s Hospital', 'KwaZulu-Natal', 'Neurology'),
(184, 'Life St Mary’s Hospital', 'KwaZulu-Natal', 'Orthopedics'),
(185, 'Life St Mary’s Hospital', 'KwaZulu-Natal', 'General Medicine'),
(186, 'Life Chatsmed Garden Hospital', 'KwaZulu-Natal', 'ICU'),
(187, 'Life Chatsmed Garden Hospital', 'KwaZulu-Natal', 'Emergency'),
(188, 'Life Chatsmed Garden Hospital', 'KwaZulu-Natal', 'Surgical'),
(189, 'Life Chatsmed Garden Hospital', 'KwaZulu-Natal', 'Maternity'),
(190, 'Life Chatsmed Garden Hospital', 'KwaZulu-Natal', 'Pediatrics'),
(191, 'Life Wilmed Park Hospital', 'North West', 'Cardiology'),
(192, 'Life Wilmed Park Hospital', 'North West', 'Oncology'),
(193, 'Life Wilmed Park Hospital', 'North West', 'Neurology'),
(194, 'Life Wilmed Park Hospital', 'North West', 'Orthopedics'),
(195, 'Life Wilmed Park Hospital', 'North West', 'General Medicine'),
(196, 'Life Queenstown Private Hospital', 'Eastern Cape', 'ICU'),
(197, 'Life Queenstown Private Hospital', 'Eastern Cape', 'Emergency'),
(198, 'Life Queenstown Private Hospital', 'Eastern Cape', 'Surgical'),
(199, 'Life Queenstown Private Hospital', 'Eastern Cape', 'Maternity'),
(200, 'Life Queenstown Private Hospital', 'Eastern Cape', 'Pediatrics')
;
